#!/bin/sh
# bootstrap-engine — resolve a tjs engine that can RUN scripts/build-tjs.cjs, on a
# machine that does not have one yet, without node.
#
# THE PROBLEM. Running build-tjs.cjs under tjs requires a tjs. On a tjs-cache MISS a
# leg has none, so "get node out of the engine build" needs an engine that predates the
# build. Nothing new has to be published to get one: .github/workflows/release.yml's
# `templates-pack` job already ships ONE blob of gzip'd bare tjs engines plus a manifest
# giving {offset,length,sha256} per target, covering 40 targets — every machine that
# builds an engine, because the set of engine-building machines IS the set of legs. One
# HTTP range request yields one complete, self-contained, sha256-verifiable engine.
#
# THE ONE RULE: `build-tjs.cjs` must never call this. It is the program being
# bootstrapped, and a bootstrap its own target invokes cannot run on the cache miss it
# exists for. The resolver lives outside it, in the CALLER. (Pinned by
# test/bootstrap-engine.test.cjs, at both ends.)
#
# ACCEPTANCE IS THE FLOOR PROBE, NOT THE PIN. The cheap check — comparing the pack
# manifest's recorded txiki pin against ours — is VACUOUS: scripts/templates-drift.mjs
# records that the txiki pin has not moved since 2026-07-06 while the patch stack moves
# weekly, so it passes on a three-week-old engine missing every fix since. That is the precise bug templates-drift
# exists to catch, and writing it here would be a gate that cannot fail. Acceptance is
# instead scripts/engine-api-floor.cjs's real probe, GENERATED by the candidate engine
# itself (through HEAD's node-shim loader, which also proves the loader runs on it) and
# required to print `tjs-shim-ok`.
#
# A CACHE HIT IS BYTES FROM SOMEWHERE ELSE. Step 4 sha256-verifies what it fetched, and
# step 3 now verifies what it found: the digest is in the COMMITTED manifest, keyed by
# target, so re-checking a cache entry costs one hash and no network. It is the ONLY
# check a cross-target hit can get (the floor probe cannot run on another machine's
# binary), and it is a different property from the probe same-host — "this is the binary
# the manifest names", not "an engine runs here" — so both run. A mismatch is loud, the
# entry is deleted, and the resolve FALLS THROUGH to a fresh fetch: a cache tarball that
# came back short is recoverable in one range request, and refusing would turn that into
# a red leg.
#
# THE BASE CASE IS DERIVED, NOT DECLARED. A brand-new alpine arch or VM guest OS has no
# published slice. This asks the pinned manifest whether <target> is in the pack; absent
# means one loud line and exit 3, and that leg builds its FIRST engine under node exactly
# once before the next release makes it self-hosting. Nothing is hand-maintained, so the
# exception cannot rot and disappears by itself. test/bootstrap-engine.test.cjs pins the
# fallback set against the manifest so a hand-added exception, reached for to dodge a
# real failure, goes red.
#
# POSIX sh, deliberately: this runs in alpine containers and in minimal VM guests where
# bash may be absent. No bashisms, no arrays, no `local`.
#
# USAGE
#   scripts/bootstrap-engine.sh                -> print a usable engine's path (stdout)
#   scripts/bootstrap-engine.sh --plan         -> print how it WOULD resolve; no network
#   scripts/bootstrap-engine.sh --print-target -> print this host's canonical target
#   scripts/bootstrap-engine.sh --print-cache  -> print the cache root it would use
# EXIT
#   0  resolved (or planned)        1  refused, loudly and specifically
#   2  usage                        3  no slice for this target: build it under node once
set -eu

REPO=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
MANIFEST=${CLODE_BOOTSTRAP_MANIFEST:-$REPO/scripts/bootstrap-engine.manifest.json}
# The token scripts/engine-api-floor.cjs prints on success. Spelled here because sh
# cannot require a CJS module; test/bootstrap-engine.test.cjs pins this literal against
# that module's OK_TOKEN, so the two cannot drift apart silently.
OK_TOKEN='tjs-shim-ok'
# The known-answer test for whichever sha256 tool this host has. Hashing is where this
# has silently gone wrong before (a pure-JS verifier that hung; a "sha256" that was not
# one), so no digest is trusted until the tool reproduces a digest we already know.
KAT_INPUT='clode-bootstrap-engine'
KAT_SHA='4c47dad47a8caaf13bef557ee0c00f8e3f41fc13145bc44b9612440fa1ea0472'
RELEASE_BASE_DEFAULT='https://github.com/schmonz/clode/releases/download'

TMP=$(mktemp -d "${TMPDIR:-/tmp}/clode-bootstrap.XXXXXX")
trap 'rm -rf "$TMP"' EXIT INT TERM HUP

note() { printf '%s\n' "$*" >&2; }
die() { printf '%s\n' "$*" >&2; exit 1; }

usage() {
  note "usage: bootstrap-engine.sh [--plan|--print-target|--print-cache]"
  exit 2
}

# --- the pinned manifest ----------------------------------------------------
# A targeted reader, not a JSON parser: the file is COMMITTED here and its shape is
# pinned by test/bootstrap-engine.test.cjs, so two awk field-pulls are enough and buy
# us no jq dependency on a guest that has none.

json_str() {  # $1 = a top-level string/number key
  awk -v k="$1" '
    { line=$0; gsub(/^[ \t]+|[ \t]+$/, "", line)
      if (index(line, "\"" k "\":") == 1) {
        sub(/^"[^"]*"[ \t]*:[ \t]*/, "", line); sub(/,$/, "", line)
        gsub(/^"|"$/, "", line); print line; exit
      } }' "$MANIFEST"
}

manifest_slice() {  # $1 = target -> "<offset> <length> <sha256>", or nothing
  awk -v t="$1" '
    { line = $0; gsub(/^[ \t]+|[ \t]+$/, "", line)
      if (!inside) {
        if (line == "\"" t "\": {" || line == "\"" t "\":{") inside = 1
        next
      }
      if (line == "}," || line == "}") { inside = 0; next }
      if (index(line, "\"sha256\":") == 1) { v = line; sub(/^"sha256"[ \t]*:[ \t]*"/, "", v); sub(/".*$/, "", v); sha = v }
      else if (index(line, "\"offset\":") == 1) { v = line; sub(/^"offset"[ \t]*:[ \t]*/, "", v); sub(/,$/, "", v); off = v }
      else if (index(line, "\"length\":") == 1) { v = line; sub(/^"length"[ \t]*:[ \t]*/, "", v); sub(/,$/, "", v); len = v }
    }
    END { if (sha != "" && off != "" && len != "") print off " " len " " sha }' "$MANIFEST"
}

# --- this host's canonical target -------------------------------------------
# scripts/canonical-name.cjs is the ONE vocabulary, and it cannot be called from here
# (no node). What makes the duplication safe is that a WRONG answer is loud, never
# wrong-but-quiet: a target this table spells differently is simply absent from the
# pack, so it takes the fallback path and names itself. CI passes CLODE_BOOTSTRAP_TARGET
# from the leg descriptor, which is the real source of truth for a leg.
canon_target() {
  if [ -n "${CLODE_BOOTSTRAP_TARGET:-}" ]; then printf '%s\n' "$CLODE_BOOTSTRAP_TARGET"; return 0; fi
  host_target
}

host_target() {
  ct_os=$(uname -s 2>/dev/null | tr 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' 'abcdefghijklmnopqrstuvwxyz')
  case "$ct_os" in
    darwin) ct_os=macos ;;
    mingw*|msys*|cygwin*|windows*) ct_os=windows ;;
    dragonfly) ct_os=dragonflybsd ;;
  esac
  ct_arch=$(uname -m 2>/dev/null)
  case "$ct_arch" in
    x86_64|amd64|x64) ct_arch=amd64 ;;
    aarch64|arm64) ct_arch=arm64 ;;
    i386|i486|i586|i686|x86|ia32) ct_arch=i386 ;;
    powerpc|ppc|macppc) ct_arch=ppc ;;
    armv7*|earmv7*) ct_arch=armv7 ;;
  esac
  printf '%s-%s\n' "$ct_os" "$ct_arch"
}

# --- the cache root ---------------------------------------------------------
# Mirrors libexec/clode-paths.cjs's clodeCacheDir precedence exactly (CLODE_CACHE >
# CLODE_STATE_ROOT > XDG_CACHE_HOME > HOME). test/bootstrap-engine.test.cjs compares
# this function's answer with that module's for every branch, so a fourth spelling of
# XDG cannot appear here unnoticed.
cache_root() {
  if [ -n "${CLODE_CACHE:-}" ]; then printf '%s\n' "$CLODE_CACHE"; return 0; fi
  if [ -n "${CLODE_STATE_ROOT:-}" ]; then printf '%s/cache/clode\n' "$CLODE_STATE_ROOT"; return 0; fi
  if [ -n "${XDG_CACHE_HOME:-}" ]; then printf '%s/clode\n' "$XDG_CACHE_HOME"; return 0; fi
  printf '%s/.cache/clode\n' "${HOME:-}"
}

# --- what counts as an engine ------------------------------------------------
# A REGULAR file that is executable. The `-f` is the whole point: `[ -x <a directory> ]`
# is TRUE in every sh, and every candidate below can legitimately name a directory.
is_engine_file() { [ -f "$1" ] && [ -x "$1" ]; }

# --- step 2: an engine this checkout already built --------------------------
# CLODE_TJS_OUT is the explicit output DIRECTORY every CI cross-build already sets --
# scripts/build-tjs.cjs:203 calls it `outDir`, creates it, and copies the finished engine
# into it as tjs / tjs.exe. It is NOT a path to the binary, and reading it as one was a
# real bug: `[ -x $CLODE_TJS_OUT ]` is true for the directory, so on a tjs-cache MISS --
# exactly when a leg needs this -- the resolver used to hand back the empty output
# directory as "the engine", and the leg would have died exec'ing it a long way from here.
# The scratch path is NOT recomputed here: scripts/platform-tag.cjs owns it (its linux
# token comes from the glibc the running node was COMPILED against, which sh cannot know),
# so we ASK it when a node happens to be present and skip the step entirely when one is
# not. A node-free host simply has no locally built engine to find, which is the truth.
local_engine() {
  if [ -n "${CLODE_TJS_OUT:-}" ]; then
    for le_name in tjs tjs.exe; do
      if is_engine_file "$CLODE_TJS_OUT/$le_name"; then printf '%s\n' "$CLODE_TJS_OUT/$le_name"; return 0; fi
    done
  fi
  le_node=${CLODE_NODE:-}
  if [ -z "$le_node" ]; then le_node=$(command -v node 2>/dev/null || :); fi
  if [ -n "$le_node" ] && [ -x "$le_node" ]; then
    le_path=$("$le_node" -p "require('$REPO/scripts/platform-tag.cjs').tjsBin('$REPO')" 2>/dev/null || :)
    if [ -n "$le_path" ] && is_engine_file "$le_path"; then printf '%s\n' "$le_path"; return 0; fi
  fi
  return 0
}

# --- sha256, known-answer tested before it is trusted -----------------------
HASHER=
HASHER_PICKED=
KAT_TRIED=
KAT_EXPLICIT=

hash_file() {
  eval "$HASHER \"\$1\"" 2>/dev/null | tr -c '0-9a-f' '\n' | grep -E '^[0-9a-f]{64}$' | head -n 1
}

try_hasher() {
  th_word=${1%% *}
  command -v "$th_word" >/dev/null 2>&1 || return 1
  HASHER=$1
  th_got=$(hash_file "$TMP/kat")
  if [ "$th_got" = "$KAT_SHA" ]; then return 0; fi
  HASHER=
  KAT_TRIED="$KAT_TRIED
  $1 -> ${th_got:-(no 64-hex digest in its output)}"
  return 1
}

# Choose a hasher ONCE per run and REPORT, rather than die. Two callers want different
# verdicts from the same question: the fetch path cannot proceed without a digest (it
# dies, below), while the cache path treats "cannot verify" as a reason to distrust one
# cache entry, not as a reason to fail the whole resolve.
pick_hasher() {
  if [ -n "$HASHER_PICKED" ]; then
    if [ -n "$HASHER" ]; then return 0; fi
    return 1
  fi
  HASHER_PICKED=1
  HASHER=
  KAT_TRIED=
  printf '%s' "$KAT_INPUT" > "$TMP/kat"
  if [ -n "${CLODE_SHA256:-}" ]; then
    if try_hasher "$CLODE_SHA256"; then return 0; fi
    KAT_EXPLICIT=1
    return 1
  fi
  if try_hasher 'sha256sum' || try_hasher 'shasum -a 256' || try_hasher 'sha256 -q' \
    || try_hasher 'openssl dgst -sha256' || try_hasher 'cksum -a sha256'; then return 0; fi
  return 1
}

require_hasher() {
  if pick_hasher; then return 0; fi
  if [ -n "$KAT_EXPLICIT" ]; then
    die "bootstrap: CLODE_SHA256=$CLODE_SHA256 failed its known-answer test.$KAT_TRIED
  sha256 of '$KAT_INPUT' must be $KAT_SHA.
  A tool that cannot reproduce a digest we already know must not be used to verify a
  downloaded engine — refusing rather than trusting it."
  fi
  die "bootstrap: no working sha256 tool on this host, so a downloaded engine cannot be
  verified and will not be used.$KAT_TRIED
  Install one (sha256sum / shasum / openssl / cksum -a sha256), or point CLODE_SHA256 at
  one, or set CLODE_TJS to an engine you already trust."
}

# --- step 3's verification --------------------------------------------------
# A CACHE HIT IS BYTES FROM SOMEWHERE ELSE, and until this landed nothing hashed them.
# Same-host, accept()'s floor probe below proves an engine RUNS here — real, but a
# different property from "this is the binary the pinned manifest names". Cross-target
# there was no check at all, because the probe cannot run on another machine's binary;
# the digest is the only check available there, which makes it the case most worth
# closing. f5d18ea gave that teeth: ~/.cache/clode/bootstrap now round-trips through
# actions/cache — tarred, uploaded, restored into a DIFFERENT run — and truncation and a
# restored-wrong entry both survive the `-x` test that used to be the whole gate.
#
# The idiom is scripts/build-tjs.cjs's provisionCosmocc(): hash the cached artifact
# whether or not THIS run downloaded it, and on a mismatch remove it. One deliberate
# difference — cosmocc throws, this FALLS THROUGH to a fresh fetch. A cache tarball that
# came back short is recoverable in one range request, and failing the resolve would turn
# a recoverable condition into a red leg. Loud either way: a cache that silently re-fetches
# is a mystery, and a mystery is how this gets quietly disabled later.
#
# Costs no network: the expected digest is in the COMMITTED manifest, keyed by target.
cache_is_authentic() {  # $1 = the cached engine
  if [ -z "$SLICE" ]; then
    note "bootstrap: the cached $TARGET engine at $1 cannot be verified — pack $TAG's manifest has no $TARGET slice to compare it against."
    note "bootstrap: an entry nothing can vouch for is not used; the base-case path below says what to do instead."
    return 1
  fi
  ca_want=${SLICE##* }
  if ! pick_hasher; then
    note "bootstrap: the cached $TARGET engine at $1 cannot be verified — no sha256 tool on this host passed its known-answer test.$KAT_TRIED"
    note "bootstrap: an unverifiable engine is not used just because it is already on disk; set CLODE_TJS to one you trust."
    return 1
  fi
  ca_got=$(hash_file "$1")
  if [ "$ca_got" = "$ca_want" ]; then return 0; fi
  note "bootstrap: the cached $TARGET engine at $1 does not match the sha256 pack $TAG records for it."
  note "bootstrap:   expected $ca_want"
  note "bootstrap:   got      ${ca_got:-(no digest)}"
  note "bootstrap: discarding it and falling through to a fresh fetch. Cache corruption is"
  note "bootstrap: recoverable in one range request — and a bad entry that is merely SKIPPED"
  note "bootstrap: is sticky in exactly the way step 4 refuses to let a bad fetch become."
  rm -f "$1"
  return 1
}

# --- the network ------------------------------------------------------------
fetch_range() {  # url start end out
  if command -v curl >/dev/null 2>&1; then
    if curl -fsSL --retry 3 -r "$2-$3" -o "$4" "$1"; then return 0; fi
    return 1
  fi
  if command -v wget >/dev/null 2>&1; then
    if wget -q --header="Range: bytes=$2-$3" -O "$4" "$1"; then return 0; fi
    return 1
  fi
  die "bootstrap: neither curl nor wget is on this host, so the pinned engine slice
  cannot be fetched. Install one, or set CLODE_TJS to an engine you already have."
}

inflate() {  # in out
  if command -v gzip >/dev/null 2>&1; then
    if gzip -dc < "$1" > "$2"; then return 0; fi
    return 1
  fi
  if command -v gunzip >/dev/null 2>&1; then
    if gunzip -c < "$1" > "$2"; then return 0; fi
    return 1
  fi
  die "bootstrap: no gzip/gunzip on this host; the pack ships each engine as a gzip
  member and there is nothing here to inflate it with."
}

# --- acceptance -------------------------------------------------------------
# Generated BY the candidate, through HEAD's node-shim loader: one run proves the loader
# works on this engine, the next proves the engine carries every binding the blobulated
# runtime needs. No second copy of the binding list lives here.
accept() {
  ac_tjs=$1
  if ! "$ac_tjs" run "$REPO/libexec/node-shim/loader.cjs" \
      "$REPO/scripts/engine-api-floor.cjs" --emit-check > "$TMP/floor.js" 2> "$TMP/gen.err"; then
    die "bootstrap: $ac_tjs could not run HEAD's node-shim loader to generate the engine
  API floor check, so it cannot host scripts/build-tjs.cjs either.
  target $TARGET, bootstrap pack $TAG
$(cat "$TMP/gen.err" 2>/dev/null || :)
  Remedies: cut a release so the pack carries an engine built from these sources, or set
  CLODE_TJS to an engine you built yourself."
  fi
  if [ ! -s "$TMP/floor.js" ]; then
    die "bootstrap: generating the engine API floor check under $ac_tjs produced nothing.
  An empty check would accept any engine at all, so this refuses instead."
  fi
  ac_rc=0
  ac_out=$("$ac_tjs" run "$TMP/floor.js" 2>&1) || ac_rc=$?
  case "$ac_out" in
    *"$OK_TOKEN"*)
      if [ "$ac_rc" -eq 0 ]; then return 0; fi ;;
  esac
  die "bootstrap: $ac_tjs does not meet HEAD's engine API floor.
  target $TARGET, bootstrap pack $TAG
  ${ac_out:-(the probe printed nothing; exit $ac_rc)}
  This is the check that is SUPPOSED to go red the day HEAD's node-shim outruns the last
  release — it is a finding, not a flake. Two remedies, both real:
    * cut a release, so the templates pack carries an engine built from these sources;
    * set CLODE_TJS to an engine built from this tree (node scripts/build-tjs.cjs)."
}

emit() {  # how path
  if [ "$MODE" = '--plan' ]; then printf '%s %s\n' "$1" "$2"; exit 0; fi
  if [ "$TARGET" = "$HOST" ]; then
    accept "$2"
  else
    # A CROSS fetch (design call site #7: the runner pulls a guest's slice into the
    # workspace and the guest runs it). The floor probe CANNOT run here — these bytes are
    # for another machine — so say that rather than skipping a check in silence. The
    # probe is not lost: the machine that runs this engine resolves through this same
    # script, where its target IS its host and the probe fires.
    note "bootstrap: NOT running the engine API floor probe — this slice is $TARGET and this host is $HOST."
    note "bootstrap: acceptance is DEFERRED to the $TARGET machine, which must resolve through this same script; the probe runs there."
  fi
  printf '%s\n' "$2"
  exit 0
}

# --- main -------------------------------------------------------------------
MODE=${1:---resolve}
case "$MODE" in
  --resolve|--plan|--print-target|--print-cache) ;;
  -h|--help) usage ;;
  *) note "bootstrap: unknown argument '$MODE'"; usage ;;
esac

TARGET=$(canon_target)
HOST=$(host_target)
if [ "$MODE" = '--print-target' ]; then printf '%s\n' "$TARGET"; exit 0; fi
CACHE=$(cache_root)
if [ "$MODE" = '--print-cache' ]; then printf '%s\n' "$CACHE"; exit 0; fi

if [ ! -f "$MANIFEST" ]; then
  die "bootstrap: the pinned pack manifest is missing: $MANIFEST
  It is committed in this repo on purpose — it IS the pin, and it is what says which
  release's bytes to trust. A checkout without it cannot bootstrap anything."
fi
TAG=$(json_str bootstrapTag)
BLOB=$(json_str blob)
if [ -z "$TAG" ] || [ -z "$BLOB" ]; then
  die "bootstrap: $MANIFEST names no bootstrapTag/blob, so there is no published pack to
  fetch from. Re-pin it from a release's templates-<pin>.json."
fi

EXE=
case "$TARGET" in windows-*) EXE='.exe' ;; esac

# Steps 1 and 2 name a HOST-NATIVE binary, so they answer only for the HOST's own
# target. The design's call site #7 is why that distinction has to be made out loud: the
# ubuntu runner fetches a NetBSD or Haiku GUEST's slice into the workspace for the guest
# to use, and handing that fetch the runner's own x86-64 ELF would rsync a binary into a
# guest that cannot run it — a failure that lands inside the VM, a long way from here.
if [ "$TARGET" = "$HOST" ]; then
  # 1. an engine the operator or CI named outright.
  if [ -n "${CLODE_TJS:-}" ]; then
    if ! is_engine_file "$CLODE_TJS"; then
      die "bootstrap: CLODE_TJS is set to '$CLODE_TJS', which is not an executable file.
  Refusing rather than quietly resolving something else: an engine selection that is
  silently ignored is how a build ends up testing a binary nobody chose."
    fi
    emit env "$CLODE_TJS"
  fi
  # 2. an engine this checkout already built.
  LOCAL=$(local_engine)
  if [ -n "$LOCAL" ]; then emit local "$LOCAL"; fi
elif [ -n "${CLODE_TJS:-}" ] || [ -n "${CLODE_TJS_OUT:-}" ]; then
  note "bootstrap: target $TARGET is not this host ($HOST), so CLODE_TJS/CLODE_TJS_OUT are not candidates — they name a $HOST binary."
fi

# The manifest's expectation for this target, read BEFORE step 3 because that is what a
# cache hit is verified against. A committed-file read, so it costs nothing and reaches
# no network; the base-case verdict on an EMPTY answer stays in step 4, below, where it
# cannot preempt steps 1 and 2.
SLICE=$(manifest_slice "$TARGET")

# 3. a slice this host already fetched and verified — re-verified HERE, every time,
# because "already on disk" says nothing about whose disk or which run.
CACHED="$CACHE/bootstrap/$TAG/$TARGET/tjs$EXE"
if is_engine_file "$CACHED"; then
  # --plan describes ROUTING, not acceptance: it deliberately does not run the floor
  # probe either (see emit), and a dry run that deletes a cache entry would be a
  # surprising thing for a no-network flag to do.
  if [ "$MODE" = '--plan' ]; then emit cache "$CACHED"; fi
  if cache_is_authentic "$CACHED"; then emit cache "$CACHED"; fi
fi

# 4. the pinned pack.
if [ -z "$SLICE" ]; then
  note "bootstrap: no $TARGET in pack $TAG — this leg is building its FIRST engine under node; it self-hosts from the next release."
  note "bootstrap: that is the expected base case for a new alpine arch or a new VM guest OS, not a broken build."
  note "bootstrap: if this host simply named itself wrong, pass the leg's real target in CLODE_BOOTSTRAP_TARGET."
  if [ "$MODE" = '--plan' ]; then printf 'fallback %s %s\n' "$TARGET" "$TAG"; fi
  exit 3
fi
if [ "$MODE" = '--plan' ]; then printf 'fetch %s %s\n' "$TARGET" "$TAG"; exit 0; fi

OFFSET=${SLICE%% *}
REST=${SLICE#* }
LENGTH=${REST%% *}
WANT_SHA=${REST#* }
END=$((OFFSET + LENGTH - 1))

require_hasher

BASE=${CLODE_RELEASE_BASE:-$RELEASE_BASE_DEFAULT}
URL="$BASE/$TAG/$BLOB"
case "$URL" in /*) URL="file://$URL" ;; esac

note "bootstrap: fetching $TARGET from $TAG (bytes $OFFSET-$END of $BLOB)"
if ! fetch_range "$URL" "$OFFSET" "$END" "$TMP/slice.gz"; then
  die "bootstrap: could not fetch bytes $OFFSET-$END of $URL.
  The pinned release must keep serving its templates pack; a deleted or re-published
  release breaks every bootstrap. Re-pin scripts/bootstrap-engine.manifest.json, or set
  CLODE_TJS to an engine you already have."
fi
GOT_LEN=$(wc -c < "$TMP/slice.gz" | tr -d ' ')
if [ "$GOT_LEN" != "$LENGTH" ]; then
  die "bootstrap: asked for $LENGTH bytes of $BLOB and got $GOT_LEN.
  A server that ignores Range hands back the WHOLE 130MB pack, which is not this
  target's engine. Refusing rather than inflating whatever arrived."
fi
if ! inflate "$TMP/slice.gz" "$TMP/tjs"; then
  die "bootstrap: the fetched slice for $TARGET did not inflate as gzip.
  Each pack member is an independent gzip stream, so this means the bytes are not the
  ones the manifest describes."
fi
GOT_SHA=$(hash_file "$TMP/tjs")
if [ "$GOT_SHA" != "$WANT_SHA" ]; then
  die "bootstrap: sha256 mismatch for $TARGET in pack $TAG.
  expected $WANT_SHA
  got      ${GOT_SHA:-(no digest)}
  These bytes are NOT the engine the pinned manifest describes, so they are discarded
  rather than cached — a bad engine that reaches the cache becomes a sticky bad engine."
fi

mkdir -p "$CACHE/bootstrap/$TAG/$TARGET"
cp "$TMP/tjs" "$CACHE/bootstrap/$TAG/$TARGET/.tjs$EXE.$$"
chmod 755 "$CACHE/bootstrap/$TAG/$TARGET/.tjs$EXE.$$"
mv -f "$CACHE/bootstrap/$TAG/$TARGET/.tjs$EXE.$$" "$CACHED"
emit fetched "$CACHED"
